### ISSUE TITLE
Migrate enzyme tests to @testing-library/react

### ISSUE THREAD

**Issue by petermakowski** [canonical/react-components#750]
We still have a few enzyme tests remaining that should be migrated to @testing-library/react.

This is blocking React v18 upgrade as [enzyme doesn't support React v18](https://github.com/enzymejs/enzyme/issues/2524)

Tasks from below can be converted to Issues as marked as completed once done.

## List of enzyme tests to migrate
- [ ] Tabs/Tabs.test.tsx
- [ ] AccordionSection/AccordionSection.test.tsx
- [ ] Pagination/Pagination.test.tsx
- [ ] ActionButton/ActionButton.test.tsx
- [ ] Form/Form.test.tsx
- [ ] Tooltip/Tooltip.test.tsx
- [ ] Strip/Strip.test.tsx
- [ ] Card/Card.test.tsx
- [ ] ArticlePagination/ArticlePagination.test.tsx
- [ ] TableCell/TableCell.test.tsx
- [ ] TableRow/TableRow.test.tsx
- [ ] MainTable/MainTable.test.tsx
- [ ] Input/Input.test.tsx
- [ ] Notification/Notification.test.tsx
- [ ] Accordion/Accordion.test.tsx
- [ ] Chip/Chip.test.tsx
- [ ] ContextualMenu/ContextualMenu.test.tsx
- [ ] ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx
- [ ] Label/Label.test.tsx
- [ ] Slider/Slider.test.tsx
- [ ] Spinner/Spinner.test.tsx
- [ ] PasswordToggle/PasswordToggle.test.tsx
- [ ] Field/Field.test.tsx
- [ ] Row/Row.test.tsx
- [ ] Textarea/Textarea.test.tsx
- [ ] Button/Button.test.tsx
- [ ] Link/Link.test.tsx
- [ ] SearchAndFilter/FilterPanelSection/FilterPanelSection.test.tsx
- [ ] SearchAndFilter/SearchAndFilter.test.tsx
- [ ] Table/Table.test.tsx
- [ ] List/List.test.tsx
- [ ] Select/Select.test.tsx
- [ ] Icon/Icon.test.tsx
- [ ] Modal/Modal.test.tsx
- [ ] CodeSnippet/CodeSnippet.test.tsx
- [ ] CheckableInput/CheckableInput.test.tsx
- [ ] TableHeader/TableHeader.test.tsx
- [ ] SearchBox/SearchBox.test.tsx
- [ ] Col/Col.test.tsx

## Once all the above is complete, we can remove enzyme from `react-components`
- [ ] setup/util files: ./src/testing/utils.tsx ./src/setupTests.js, package.json, yarn.lock
